server:
  port: 9001
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver
    profile:
      active: local
      include: secret
  jpa:
    hibernate:
      ddl-auto: create
